website/views.py
from flask import Blueprint
from flask import render_template, request, flash, redirect, url_for
from .models import Customer, Admin
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
import logging




views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def auth():
    if request.method == "POST":
        admin_login_name = request.form.get("admin_name")
        admin_login_password = request.form.get("admin_password")
        admin = Admin.query.filter_by(name=admin_login_name).first()
        if admin:
            if check_password_hash(admin.password, admin_login_password):
                login_user(admin, remember=True)
                return redirect("/alle_kunden")
            else:
                flash("Passwort stimmt nicht überein.", category="error")
        else:
            flash("Es existiert kein Nutzer mit diesem namen. ", category="error")

    return render_template("auth.html", admin=current_user)

@views.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Erfolgreich Abgemeldet.", category="success")
    return redirect(url_for("views.auth"))


@views.route("/mitglied_auth", methods=["GET","POST"])
def mitglied_auth():
    return render_template("mitglied_auth.html")


@views.route("/alle_kunden", methods=["GET", "POST"])
@login_required
def alle_kunden():
    if request.method == "POST" and request.form["del"]:
        kunde_id = request.form.get("del")
        db.engine.execute(f"DELETE FROM customer WHERE id = {kunde_id}")
        db.session.commit()
        flash("Kunde entfernt.", category="success")
        return redirect(url_for("views.alle_kunden"))
    else:
        return render_template("alle_kunden.html", admin=current_user)


@views.route("/kunde_bearbeiten", methods=["GET", "POST"])
@login_required
def kunde_bearbeiten():
    if request.method == 'POST' and request.form.get("edit"):
        kunde_id = request.form["edit"]
        kunde = Customer.query.filter_by(id=kunde_id).first()
        return render_template("kunde_bearbeiten.html", admin=current_user,
                                                        kunde_firstName=kunde.firstName,
                                                        kunde_lastName=kunde.lastName,
                                                        kunde_id=kunde.id,
                                                        kunde_email = kunde.email,
                                                        kunde_birthDate = kunde.birthDate)

    elif request.method == 'POST' and request.form.get("save"):
        kunde_id = request.form["save"]
        kunde = Customer.query.filter_by(id=kunde_id).first()
        kunde_email_new = request.form["email"]
        kunde_firstName_new = request.form["firstName"]
        kunde_lastName_new = request.form["lastName"]
        kunde_birthDate_new = request.form["birthDate"]

        logging.basicConfig()
        logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)
        db.engine.execute("""UPDATE customer SET  
                                            email = :email, 
                                            firstName = :firstName, 
                                            lastName = :lastName, 
                                            birthDate = :birthDate 
                                            WHERE id = :id""", {

                                            "email": kunde_email_new,
                                            "firstName": kunde_firstName_new,
                                            "lastName": kunde_lastName_new,
                                            "birthDate": kunde_birthDate_new,
                                            "id": kunde_id
                                            })
        db.session.commit()
        return redirect(url_for("views.alle_kunden"))

    return render_template("kunde_bearbeiten.html")


@views.route("/search", methods=["GET", "POST"])
@login_required
def search():
    char = "@"
    if request.method == 'POST' and request.form["searchbar"]:
        global keyword
        keyword = request.form.get("searchbar")
        global results
        if keyword.isalpha() and char not in keyword:
            results = db.engine.execute(f"""
                                SELECT * FROM customer WHERE firstName LIKE '%{keyword}%' OR lastName LIKE '%{keyword}%'
                                """)

        elif char in keyword:
            results = db.engine.execute(f"""
                                SELECT * FROM customer WHERE email LIKE '%{keyword}%'
                                """)

        elif keyword.isnumeric():
            results = db.engine.execute(f"""
                                SELECT * FROM customer WHERE id LIKE '{keyword}'
                                """)

        elif keyword == "":
            return redirect(url_for("views.alle_kunden"))

    return render_template("alle_kunden_search.html", admin=current_user, results=results)




@views.route("/anlegen", methods=["GET", "POST"])
@login_required
def kunde_anlegen():
    if request.method == "POST":
        email = request.form.get("email")
        firstName = request.form.get("firstName")
        lastName = request.form.get("lastName")
        birthDate = request.form.get("birthDate")


        if len(firstName) < 2:
            flash("Der Vorname muss mindestens zwei Buchstaben haben.", category="error")
        elif firstName[0].isalpha() == False:
            flash("Der erste Charakter eines Vornamens muss ein Buchstabe sein", category="error")
        elif lastName[0].isalpha() == False:
            flash("Der erste Charakter eines Nachnamens muss ein Buchstabe sein", category="error")
        elif lastName == "":
            flash("Bitte gib den Nachnamen des Kunden ein.", category="error")
        elif birthDate == "":
            flash("Bitte gib das Geburtsdatum an.")
        else:
            neuer_kunde = Customer(email=email, firstName=firstName, lastName=lastName, birthDate=birthDate, admin_id=current_user.id)
            db.session.add(neuer_kunde)
            db.session.commit()
            flash("Kunde erstellt!", category="success")

    return render_template("kunde_anlegen.html")


@views.route("/admin_anlegen", methods=["POST", "GET"])
def admin_anlegen():
    if request.method == "POST":
        admin_name = request.form["admin1_name"]
        admin_email = request.form["admin1_email"]
        password = request.form["admin1_password"]
        password_confirm = request.form["admin1_password_confirm"]
        admin_email_candidate = Admin.query.filter_by(email=admin_email).first()
        if admin_email_candidate:
            flash("Diese E-Mail existiert bereits.", category="error")
        elif password != password_confirm:
            flash("Die Passwörter stimmen nicht überein.", category="error")
        elif admin_name == "":
            flash("Bitte geben Sie einen Namen ein.", category="error")
        elif admin_email == "":
            flash("Bitte geben Sie eine E-Mail ein.", category="error")
        elif password == "":
            flash("Bitte geben Sie ein Passwort ein.", category="error")
        elif len(password) < 4:
            flash("Passwort ist zu kurz.", category="error")
        else:
            neuer_admin = Admin(name=admin_name, email=admin_email, password=generate_password_hash(password, method="sha256"))
            db.session.add(neuer_admin)
            db.session.commit()

            admin = Admin.query.filter_by(name=admin_name).first()
            if admin:
                if check_password_hash(admin.password, password):
                    flash("Erfolgreich angemeldet.", category="success")
                    login_user(admin, remember=True)
                    return redirect(url_for("views.alle_kunden"))
            return redirect(url_for("views.alle_kunden"))

    return render_template("create_admin.html")


@views.route("/delete_customer", methods=['POST', 'GET'])
@login_required
def delete_user():
    if request.method == "POST":
        kunde_id = request.form["delete"]
        kunde = Customer.query.filter_by(id=kunde_id).first()
        db.engine.execute(f"DELETE FROM customer WHERE id ={kunde_id}")
        db.session.commit()
        flash("Kunde entfernt.", category="success")
        return render_template("/alle_kunden")


@views.route("/alle_löschen", methods=['POST', 'GET'])
@login_required
def alle_löschen():
    admin_id = current_user.get_id()
    if request.method == 'POST' and request.form.get("delete_all_no"):
        return redirect(url_for("views.alle_kunden"))
    elif request.method == 'POST' and request.form.get("delete_all_yes"):
        db.engine.execute(f"DELETE FROM customer WHERE admin_id = {admin_id};")
        db.session.commit()

        return redirect(url_for("views.alle_kunden"))
    return render_template("alle_löschen.html", admin=current_user)





website/templates/alle_kunden.html
{% extends "index.html" %} {% block title %}Alle Kunden{% endblock %}
{% block nav %}
<div style="border-bottom:1px solid black; opacity:1;">
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom" style="background-color:white; padding-right:0px;">
    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
    >
    </button>



            <h4 style="margin-right:20px; text-shadow:5px 5px 7px rgba(0, 0, 0, 0.2); color:black; font-size:27px; margin-top:20px; margin-left:40px; text-align:left;">{% block header %}Spielwiese Kundenverwaltung{% endblock %}</h4>
            <div class="navbar-nav">

            <div class="container-search" style="s">
                <form method="post"  id="search" action="{{ url_for('views.search') }}">
                <input name="searchbar" class="search-bar-custom" type="search" placeholder="Nach Kunde suchen" aria-label="Search">
                <input class="search-btn" style="margin-right:0px;" type="image" src="https://img.icons8.com/ios/72/search-client.png" id="search-btn"><span class="svg"></span></input>
                </form>
            </div>

                <div class="nav-btns">
                 <a class="nav-link-custom kunde_anlegen-transition" style=" text-decoration:none; color:black; black;margin-top: 20px; font-size:20px; margin-left:auto;" id="kunde_anlegen" href="/anlegen">Kunde anlegen </a>
                <a class="nav-link-custom alle_kunden-transition" style=" text-decoration:none; color:black; margin-left:15px; margin-top: 20px; font-size:20px;" id="alle_kunden" href="/alle_kunden">Alle Kunden</a>
                <a class="nav-link-custom abmelden-transition dropdown-ich" style=" text-decoration:none; color:black; margin-left:15px; margin-top: 20px; font-size:20px; margin-right:0px;" id="logout">Ich</a>
                <div class="dropdown-div">
                <input class="dropdown-arrow" type="image" src="https://img.icons8.com/ios/50/000000/expand-arrow--v1.png" id="dropdown">
                    <div class="dropdown-content">
                    <a href="/">Mitglieder</a>
                    <a href="/alle_löschen">Alle Kunden löschen</a>
                    <a href="/logout">Abmelden</a>
                </div>

                </div>
                </div>
            {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'success' %}
    <div class="alert-success-custom">
    <a>{{ message }}</a>
        </div>
    {% else %}

    {% endif %} {% endfor %} {% endif %} {% endwith %}
        </div>
    </nav>

    </div>







{% endblock %}
{% block content %}
<script src="alle_kunden_script.js"></script>
<style>

  .del {
    width: 15%;
    box-sizing: border-box;
    padding: 3px;
    margin-right: 10px;
    }
        .del_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(124, 124, 124, 0);
            border-radius: 1px;
            color: rgb(202, 0, 0);
            border-width: 1px;
            padding: 3px;
            border-color: rgb(202, 0, 0);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            margin-right: 10px;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;

        }
        .del_btn:hover {
            background-color: rgb(202, 0, 0);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .edit_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(31, 147, 255, 0);
            border-radius: 1px;
            color: rgba(31, 147, 255, 1);
            border-width: 1px;
            padding: 3px;
            border-color: rgba(31, 147, 255, 1);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;
            margin-top: 5px;

        }
        .edit_btn:hover {
            background-color: rgba(31, 147, 255, 1);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .row_data {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          text-align: center;
          margin-top: 20px;
        }
        .col-custom {

        }
</style>
&nbsp;
&#160;
<ul class="list-group list-group-flush" id="kunden" xmlns="http://www.w3.org/1999/html"
    xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <table style="margin-top:130px;" class="table table-bordered table1">
    <thead>
    <tr>
      <th scope="col"><span class="col-custom">#</span></th>
      <th scope="col"><span class="col-custom">Vorname</span></th>
      <th scope="col"><span class="col-custom">Nachname</span></th>
      <th scope="col"><span style="margin-left:90px;" class="col-custom">E-Mail</span></th>
      <th scope="col"><span class="col-custom">Geburstdatum</span></th>
      <th scope="col"><span class="col-custom">Erstellungsdatum</span></th>
      <th scope="col"><span class="col-custom">ID</span></th>
      <th scope="col"><span class="col-custom">Optionen</span></th>
    </tr>
    </thead>

    {% set number = namespace(value=1) %}
  {% for kunde in admin.customers %}
<tbody>
<tr>
  <th scope="row"><span class="col-custom">{{ number.value }}</span></th>
  {% set number.value = number.value + 1 %}
  <td> <div class="row_data"  col_name="fname"> {{ kunde.firstName }} </div> </td>
  <td> <div class="row_data"  col_name="lname"> {{ kunde.lastName }} </div> </td>
  <td> <div class="row_data"  col_name="email"> {{ kunde.email }} </div> </td>
  <td> <div class="row_data"  col_name="bdate"> {{ kunde.birthDate }} </div> </td>
  <td> <div class="row_data"  col_name="cdate"> {{ kunde.creationDate }} </div> </td>
  <td> <div class="row_data"  col_name="ID"> {{ kunde.id }} </div> </td>
  <td>
    <div>
    <form method="POST" id="del_btn" action="{{ url_for('views.alle_kunden') }}" >
      <button style="width:100px; display:block; margin:auto; margin-bottom:1px;" type="submit" class="del_btn" name="del" value="{{ kunde.id }}">Löschen</button>
  </form>
    <form method="POST" id="edit_btn" action="{{ url_for('views.kunde_bearbeiten') }}">
      <button style="width:100px; display:block; margin:auto;" type="submit" class="edit_btn" name="edit" value="{{ kunde.id }}">Bearbeiten</button>
    </form>
      </div>
  </td>


</tr>

</tbody>
  {% endfor %}</ul>

  </table>



{% endblock %}

website/templates/alle_kunden_search.html
{% extends "index.html" %} {% block title %}Alle Kunden{% endblock %}
{% block content %}
<script src="alle_kunden_script.js"></script>
<style>

  .del {
    width: 15%;
    box-sizing: border-box;
    padding: 3px;
    margin-right: 10px;
    }
        .del_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(124, 124, 124, 0);
            border-radius: 1px;
            color: rgb(202, 0, 0);
            border-width: 1px;
            padding: 3px;
            border-color: rgb(202, 0, 0);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            margin-right: 10px;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;

        }
        .del_btn:hover {
            background-color: rgb(202, 0, 0);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .edit_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(31, 147, 255, 0);
            border-radius: 1px;
            color: rgba(31, 147, 255, 1);
            border-width: 1px;
            padding: 3px;
            border-color: rgba(31, 147, 255, 1);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;
            margin-top: 5px;

        }
        .edit_btn:hover {
            background-color: rgba(31, 147, 255, 1);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .row_data {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          text-align: center;
          margin-top: 20px;
        }
        .col-custom {

        }
</style>

&#160;
<ul class="list-group list-group-flush" id="kunden" xmlns="http://www.w3.org/1999/html"
    xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <table style="margin-top:130px;" class="table table-bordered table1">
    <thead>
    <tr>
      <th scope="col"><span class="col-custom">#</span></th>
      <th scope="col"><span class="col-custom">Vorname</span></th>
      <th scope="col"><span class="col-custom">Nachname</span></th>
      <th scope="col"><span style="margin-left:120px;" class="col-custom">E-Mail</span></th>
      <th scope="col"><span class="col-custom">Geburstdatum</span></th>
      <th scope="col"><span class="col-custom">Erstellungsdatum</span></th>
      <th scope="col"><span class="col-custom">ID</span></th>
      <th scope="col"><span class="col-custom">Optionen</span></th>
    </tr>
    </thead>

    {% set number = namespace(value=1) %}
  {% for row in results %}
<tbody>
<tr>
  <th scope="row"><span class="col-custom">{{ number.value }}</span></th>
  {% set number.value = number.value + 1 %}
  <td> <div class="row_data"  col_name="fname"> {{ row.firstName }} </div> </td>
  <td> <div class="row_data"  col_name="lname"> {{ row.lastName }} </div> </td>
  <td> <div class="row_data"  col_name="email"> {{ row.email }} </div> </td>
  <td> <div class="row_data"  col_name="bdate"> {{ row.birthDate }} </div> </td>
  <td> <div class="row_data"  col_name="cdate"> {{ row.creationDate }} </div> </td>
  <td> <div class="row_data"  col_name="ID"> {{ row.id }} </div> </td>
  <td>
    <div>
    <form method="POST" id="del_btn" action="{{ url_for('views.alle_kunden') }}" >
      <button style="width:100px; display:block; margin:auto; margin-bottom:1px;" type="submit" class="del_btn" name="del" value="{{ row.id }}">Löschen</button>
  </form>
    <form method="POST" id="edit_btn" action="{{ url_for('views.kunde_bearbeiten') }}">
      <button style="width:100px; display:block; margin:auto;" type="submit" class="edit_btn" name="edit" value="{{ row.id }}">Bearbeiten</button>
    </form>
      </div>
  </td>


</tr>

</tbody>
  {% endfor %}</ul>

  </table>



{% endblock %}

website/templates/alle_löschen.html
{% extends "index.html" %}
{% block content %}
<style>

  .del {
    width: 15%;
    box-sizing: border-box;
    padding: 3px;
    margin-right: 10px;
    }
        .del_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(124, 124, 124, 0);
            border-radius: 1px;
            width:200px;
            color: rgb(202, 0, 0);
            border-width: 1px;
            padding: 6px;
            border-color: rgb(202, 0, 0);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            margin-right: 10px;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;

        }
        .del_btn:hover {
            background-color: rgb(202, 0, 0);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .edit_btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(31, 147, 255, 0);
            border-radius: 1px;
            width:200px;
            color: rgba(31, 147, 255, 1);
            border-width: 1px;
            padding: 6px;
            border-color: rgba(31, 147, 255, 1);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;
            margin-top: 5px;

        }
        .edit_btn:hover {
            background-color: rgba(31, 147, 255, 1);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }
        .row_data {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          text-align: center;
          margin-top: 20px;
        }
        .div {
            text-align:center;
        }
</style>
    <h4 style="margin-top:300px;margin-bottom:40px;text-align:center;">Wollen Sie wirklich <span class="underline" style="text-decoration:underline;">ALLE</span> Kunden löschen?</h4>
<div class="div">
    <form method="post" name="delete-value" id="delete-value" action="{{ url_for('views.alle_löschen') }}">
        <button type="submit" class="del_btn" name="delete_all_no" value="NO">Nein</button>
        <button type="submit" class="edit_btn" name="delete_all_yes" value="YES">Ja</button>

 </div>
    </form>



{% endblock %}

website/templates/create_admin.html
{% extends "index.html" %}
{% block nav %}
<style>
    .anmelden-btn {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: rgba(31, 147, 255, 0);
            border-radius: 1px;
            color: rgb(31, 147, 255);
            border-width: 1px;
            padding: 10px;
            border-color: rgb(31, 147, 255);
            border-style: solid;
            cursor: pointer;
            font-weight: bold;
            margin-right: 10px;
            padding-left:20px;
            padding-right:20px;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
              transition-property: color, background-color, border-color, box-shadow;
              transition-duration: 0.15s, 0.15s, 0.15s, 0.15s;
              transition-timing-function: ease-in-out, ease-in-out, ease-in-out, ease-in-out;
              transition-delay: 0s, 0s, 0s, 0s;
  }

        .anmelden-btn:hover {
            background-color: rgba(31, 147, 255, 1);
            color: white;
            box-shadow: 5px 5px 7px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
  }
</style>
<div style="border-bottom:1px solid black; opacity:0.7;">
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom" style="background-color:white; padding-right:0px;">
    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
    >
        <span class="navbar-toggler-icon"></span>
    </button>



            <h4 style="text-shadow:5px 5px 5px rgba(0, 0, 0, 0.2); color:black; font-size:27px; margin-top:20px; margin-left:27px; text-align:center;">{% block header %}Spielwiese Kundenverwaltung{% endblock %}</h4>
            <div class="navbar-nav">




            </div>
        </nav>

</div>






{% endblock %}
{% block content %}&nbsp;

<h5 style="color:black;margin-top:120px;" align="center">Einen Admin Account erstellen:</h5>
&nbsp;{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="message-danger">
    <a>{{ message }}</a>
        </div>
    {% else %}

    {% endif %} {% endfor %} {% endif %} {% endwith %}
<form method="POST" action="{{ url_for('views.admin_anlegen') }}">
    <div class="form-group">
        <label for="admin1_name">Username</label>
        <input
                type="text"
                class="form-control"
                id="admin1_name"
                name="admin1_name"
                placeholder="Username"
        />
    </div>
    <form method="POST">
    <div class="form-group">
        <label for="admin1_email">E-mail</label>
        <input
                type="email"
                class="form-control"
                id="admin1_email"
                name="admin1_email"
                placeholder="E-Mail"
        />
    </div>
    <div class="form-group">
        <label for="admin1_password">Passwort</label>
        <input
                type="password"
                class="form-control"
                id="admin1_password"
                name="admin1_password"
                placeholder="Passwort"
        />

        &#160;
        &#160;

    <div class="form-group">
        <label for="admin1_password_confirm">Passwort bestätigen</label>
        <input
                type="password"
                class="form-control"
                id="admin1_password_confirm"
                name="admin1_password_confirm"
                placeholder="Passwort bestätigen"
        />
        <br/>
         <div align="center">
    <a href="/" class="link-secondary">Hier anmelden</a>
    </div>
        <button type="submit" class="anmelden-btn">Registrieren</button>
        </div>
    </div>
    </form>


{% endblock %}